categories:
  - title: 'ğŸš€  Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ğŸ›  Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ğŸ“š  Docs'
    label: 'docs'
  - title: 'ğŸ§°  Maintenance'
    label: 'chore'
  - title: 'ğŸ”§ setting'
    label: 'setting'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
exclude-labels:
  - 'skip-changelog'
template: |
  $CHANGES
